# Generated by Django 3.2 on 2021-05-04 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('usage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserCouples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_user_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_user_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('usercouple_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to='users.usercouples')),
                ('gender', models.CharField(max_length=15)),
                ('origin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LikedNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_names', to='users.babynames')),
                ('usercouple_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_names', to='users.usercouples')),
            ],
        ),
        migrations.CreateModel(
            name='UserNamePools',
            fields=[
                ('usercouple_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='names_pool', serialize=False, to='users.usercouples')),
                ('names', models.ManyToManyField(related_name='names_pool', to='users.BabyNames')),
            ],
        ),
    ]
