# Generated by Django 3.2 on 2021-05-02 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_rename_likednames_likedname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPartner',
            fields=[
                ('user_one', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='partner', serialize=False, to='auth.user')),
            ],
        ),
        migrations.AlterField(
            model_name='likedname',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_names', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserCouple',
        ),
    ]
