# Generated by Django 3.2 on 2021-05-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210507_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikedNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_liked_names', to='users.babynames')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_liked_names', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
