# Generated by Django 3.2 on 2021-05-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210504_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='origin',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
