# Generated by Django 3.2 on 2021-05-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210505_1440'),
        ('users', '0002_auto_20210505_2204'),
        ('users', '0003_auto_20210505_1031'),
    ]

    operations = [
    ]
