# Generated by Django 3.2 on 2021-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20210506_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likednames',
            name='matched',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
