# Generated by Django 3.2 on 2021-05-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210506_1420'),
        ('users', '0005_merge_20210506_1430'),
    ]

    operations = [
    ]
