# Generated by Django 3.2 on 2021-05-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20210506_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='likednames',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
